In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving disease_prediction.csv to disease_prediction.csv

In [ ]:
df = pd.read_csv("disease_prediction.csv")

In [ ]:
df.head()

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,2,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,3,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,4,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,5,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes

df.shape

In [ ]:
df.shape

(1000, 14)

In [ ]:
df.columns

Index(['patient_id', 'age', 'gender', 'glucose_mg_dl', 'cholesterol_mg_dl',
       'systolic_bp', 'diastolic_bp', 'bmi', 'heart_rate', 'smoking',
       'alcohol_consumption', 'physical_activity', 'family_history',
       'disease'],
      dtype='object')

In [ ]:



df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1000 non-null   int64
 1   age                  1000 non-null   int64
 2   gender               1000 non-null   object
 3   glucose_mg_dl        1000 non-null   int64
 4   cholesterol_mg_dl    1000 non-null   int64
 5   systolic_bp          1000 non-null   int64
 6   diastolic_bp         1000 non-null   int64
 7   bmi                  1000 non-null   float64
 8   heart_rate           1000 non-null   int64
 9   smoking              1000 non-null   object
 10  alcohol_consumption  1000 non-null   object
 11  physical_activity    1000 non-null   object
 12  family_history       1000 non-null   object
 13  disease              1000 non-null   object
dtypes: float64(1), int64(7), object(6)
memory usage: 109.5+ KB

In [ ]:
df.isnull().sum()

patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64

In [ ]:
df = df.drop("patient_id", axis=1)

In [ ]:
df.head()

,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes

In [ ]:
X = df.drop("disease", axis=1)

y = df["disease"]

In [ ]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1000, 12)
y shape: (1000,)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

In [ ]:
numerical_columns = [
    "age",
    "glucose_mg_dl",
    "cholesterol_mg_dl",
    "systolic_bp",
    "diastolic_bp",
    "bmi",
    "heart_rate"
]

categorical_columns = [
    "gender",
    "smoking",
    "alcohol_consumption",
    "physical_activity",
    "family_history"
]

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_columns),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_columns)
    ]
)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

In [ ]:
pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", model)
    ]
)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'glucose_mg_dl',
                                                   'cholesterol_mg_dl',
                                                   'systolic_bp',
                                                   'diastolic_bp', 'bmi',
                                                   'heart_rate']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'smoking',
                                                   'alcohol_consumption',
                                                   'physical_activity',
                                                   'family_history'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [ ]:
y_pred = pipeline.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.84

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (800, 12)
X_test: (200, 12)
y_train: (800,)
y_test: (200,)

In [ ]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'glucose_mg_dl',
                                                   'cholesterol_mg_dl',
                                                   'systolic_bp',
                                                   'diastolic_bp', 'bmi',
                                                   'heart_rate']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'smoking',
                                                   'alcohol_consumption',
                                                   'physical_activity',
                                                   'family_history'])])),
                ('classifier', LogisticRegression(max_iter=1000))])

In [ ]:
y_pred = pipeline.predict(X_test)

In [ ]:
print("Actual values:")
print(y_test.head(10).values)

print("\nPredicted values:")
print(y_pred[:10])

Actual values:
['Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No']

Predicted values:
['Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No']

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy percentage:", accuracy * 100, "%")

Accuracy: 0.84
Accuracy percentage: 84.0 %

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[81 19]
 [13 87]]

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.86      0.81      0.84       100
         Yes       0.82      0.87      0.84       100

    accuracy                           0.84       200
   macro avg       0.84      0.84      0.84       200
weighted avg       0.84      0.84      0.84       200

In [ ]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Cross-validation scores:")
print(cv_scores)

print("\nMean CV accuracy:", cv_scores.mean())
print("Standard deviation:", cv_scores.std())

Cross-validation scores:
[0.87  0.785 0.795 0.865 0.875]

Mean CV accuracy: 0.8380000000000001
Standard deviation: 0.03944616584663202

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          No       0.86      0.81      0.84       100
         Yes       0.82      0.87      0.84       100

    accuracy                           0.84       200
   macro avg       0.84      0.84      0.84       200
weighted avg       0.84      0.84      0.84       200

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[81 19]
 [13 87]]

In [ ]:
final_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", LogisticRegression(max_iter=1000))
    ]
)

final_pipeline.fit(X, y)

print("Final model trained successfully!")

Final model trained successfully!

In [ ]:
from google.colab import files

files.download("disease_logistic_model.pkl")

FileNotFoundError: Cannot find file: disease_logistic_model.pkl

In [ ]:
import joblib

joblib.dump(final_pipeline, "disease_logistic_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [ ]:
import os

print(os.path.exists("disease_logistic_model.pkl"))

True

In [ ]:
from google.colab import files

files.download("disease_logistic_model.pkl")

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, pos_label="Yes"))
print("Recall   :", recall_score(y_test, y_pred, pos_label="Yes"))
print("F1 Score :", f1_score(y_test, y_pred, pos_label="Yes"))

Accuracy : 0.84
Precision: 0.8207547169811321
Recall   : 0.87
F1 Score : 0.8446601941747572

In [ ]:
balanced_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", LogisticRegression(
            max_iter=1000,
            class_weight="balanced"
        ))
    ]
)

In [ ]:
balanced_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'glucose_mg_dl',
                                                   'cholesterol_mg_dl',
                                                   'systolic_bp',
                                                   'diastolic_bp', 'bmi',
                                                   'heart_rate']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'smoking',
                                                   'alcohol_consumption',
                                                   'physical_activity',
                                                   'family_history'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [ ]:
balanced_pred = balanced_pipeline.predict(X_test)

In [ ]:
print("Balanced Model")

print("Accuracy :",
      accuracy_score(y_test, balanced_pred))

print("Precision:",
      precision_score(y_test, balanced_pred, pos_label="Yes"))

print("Recall   :",
      recall_score(y_test, balanced_pred, pos_label="Yes"))

print("F1 Score :",
      f1_score(y_test, balanced_pred, pos_label="Yes"))

Balanced Model
Accuracy : 0.84
Precision: 0.8207547169811321
Recall   : 0.87
F1 Score : 0.8446601941747572

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "classifier__C": [0.01, 0.1, 1, 10, 100],
    "classifier__class_weight": [None, "balanced"],
    "classifier__solver": ["liblinear", "lbfgs"]
}

In [ ]:
grid_search = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan]
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['age',
                                                                          'glucose_mg_dl',
                                                                          'cholesterol_mg_dl',
                                                                          'systolic_bp',
                                                                          'diastolic_bp',
                                                                          'bmi',
                                                                          'heart_rate']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'smoking',
                                                                          'alcohol_consumption',
                                                                          'physical_activity',
                                                                          'family_history'])])),
                                       ('classifier',
                                        LogisticRegression(max_iter=1000))]),
             n_jobs=-1,
             param_grid={'classifier__C': [0.01, 0.1, 1, 10, 100],
                         'classifier__class_weight': [None, 'balanced'],
                         'classifier__solver': ['liblinear', 'lbfgs']},
             scoring='f1')

In [ ]:
print("Best parameters:")
print(grid_search.best_params_)

print("\nBest cross-validation F1:")
print(grid_search.best_score_)

Best parameters:
{'classifier__C': 0.01, 'classifier__class_weight': None, 'classifier__solver': 'liblinear'}

Best cross-validation F1:
nan

In [ ]:
tuned_pred = grid_search.predict(X_test)

In [ ]:
print("Tuned Model")

print("Accuracy :",
      accuracy_score(y_test, tuned_pred))

print("Precision:",
      precision_score(y_test, tuned_pred, pos_label="Yes"))

print("Recall   :",
      recall_score(y_test, tuned_pred, pos_label="Yes"))

print("F1 Score :",
      f1_score(y_test, tuned_pred, pos_label="Yes"))

Tuned Model
Accuracy : 0.825
Precision: 0.8095238095238095
Recall   : 0.85
F1 Score : 0.8292682926829268

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    tuned_pred
))

              precision    recall  f1-score   support

          No       0.84      0.80      0.82       100
         Yes       0.81      0.85      0.83       100

    accuracy                           0.82       200
   macro avg       0.83      0.82      0.82       200
weighted avg       0.83      0.82      0.82       200

In [ ]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, f1_score

# Get probability of "Yes"
y_prob = pipeline.predict_proba(X_test)[:, list(pipeline.classes_).index("Yes")]

# Convert actual Yes/No to 1/0
y_actual = (y_test == "Yes").astype(int)

thresholds = np.arange(0.30, 0.71, 0.05)

print("Threshold | Precision | Recall | F1")
print("-" * 40)

for threshold in thresholds:

    predictions = (y_prob >= threshold).astype(int)

    precision = precision_score(y_actual, predictions)
    recall = recall_score(y_actual, predictions)
    f1 = f1_score(y_actual, predictions)

    print(
        f"{threshold:.2f}      | "
        f"{precision:.3f}     | "
        f"{recall:.3f} | "
        f"{f1:.3f}"
    )

Threshold | Precision | Recall | F1
----------------------------------------
0.30      | 0.736     | 0.920 | 0.818
0.35      | 0.776     | 0.900 | 0.833
0.40      | 0.779     | 0.880 | 0.826
0.45      | 0.798     | 0.870 | 0.833
0.50      | 0.821     | 0.870 | 0.845
0.55      | 0.829     | 0.870 | 0.849
0.60      | 0.833     | 0.850 | 0.842
0.65      | 0.837     | 0.820 | 0.828
0.70      | 0.853     | 0.810 | 0.831

In [ ]:
threshold = 0.55

yes_index = list(pipeline.classes_).index("Yes")

y_prob = pipeline.predict_proba(X_test)[:, yes_index]

threshold_predictions = np.where(
    y_prob >= threshold,
    "Yes",
    "No"
)

In [ ]:
print(classification_report(
    y_test,
    threshold_predictions
))

              precision    recall  f1-score   support

          No       0.86      0.82      0.84       100
         Yes       0.83      0.87      0.85       100

    accuracy                           0.84       200
   macro avg       0.85      0.84      0.84       200
weighted avg       0.85      0.84      0.84       200

In [ ]:
import joblib

deployment_model = {
    "pipeline": pipeline,
    "threshold": 0.55
}

joblib.dump(
    deployment_model,
    "disease_logistic_model_v2.pkl"
)

print("Improved model saved!")

Improved model saved!

In [ ]:
from google.colab import files

files.download("disease_logistic_model_v2.pkl")